name: Sudar's blog
description: Random musings of the RNN I was born with
meta_description: "Sudar Abisheck, Neural Networks, Deep Learning, Machine learning, CUDA, CNN, LSTM, Convolutional Neural Networks, ResNet"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# markdown: maruku
# highlighter: pygments
# highlighter: rouge

logo: true
paginate: 7
baseurl: /

permalink: blog/:title/


domain_name: 'https://sudar.me'
google_analytics: 'UA-48301279-4'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: 'https://sudar.me'
author: 'Sudar Abisheck'

disqus:
  shortname: 'sudarabisheck'